

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceTypes: ["t2.micro","t3.micro"] # Multiple types for better Spot availability
    spot: true
    desiredCapacity: 2